name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 4"

jobs:
  code-quality:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - name: Obtain V from the official repository
        run: git clone https://github.com/vlang/v v --depth 1

      - name: Checkout the PDML module
        uses: actions/checkout@v4
        with:
          path: v_pdml

      - name: Build V
        run: |
          cd v && make
          ./v symlink -githubci && git clone ../v_pdml/ ~/.vmodules/v_pdml

      - name: Run tests
        run: ls && cd v_pdml && v test .

      - name: Ensure code is formatted
        run: cd v_pdml && v fmt -verify .

      - name: Ensure documentation is OK
        run: cd v_pdml && v check-md .

      - name: Ensure all examples compile
        run: cd v_pdml && v should-compile-all examples/

      - name: Ensure first example can run from an arbitrary working folder
        run: v_pdml/examples/01_from_string/example

      - name: Ensure second example can run from an arbitrary working folder
        run: v_pdml/examples/02_from_file/example
